version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
